name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint-and-type-check:
    name: Linting & Type Checking
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./magenta-mass
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: magenta-mass/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Astro type checking
        run: npx astro check
  
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./magenta-mass
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: magenta-mass/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run API tests
        run: npm run test:api
      
      - name: Run integration tests
        run: npm run test:integration
      
      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          directory: ./magenta-mass/coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
  
  e2e-tests:
    name: E2E Tests (Optional)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    defaults:
      run:
        working-directory: ./magenta-mass
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: magenta-mass/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Setup test environment
        run: |
          cp test.env.example .env.test || true
          echo "Test environment setup completed"
      
      - name: Build application
        run: npm run build
      
      - name: Start application server
        run: npm start &
        env:
          PORT: 4321
      
      - name: Wait for server to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:4321; do sleep 2; done'
      
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          CI: true
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: magenta-mass/playwright-report/
          retention-days: 7
  
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./magenta-mass
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: magenta-mass/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi
          echo "Build successful - dist directory exists"

